django_tutorial/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='index'),
    url(r'^example-module/', include('apps.example_module.urls', namespace="exampmod")),
    url(r'^iamreusable/', include('iamreusable.urls', namespace="iamreusable")),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_tutorial/views.py
import logging
from django.views.generic import TemplateView

logger = logging.getLogger(__name__)

class HomeView(TemplateView):
    template_name = "django_tutorial/home.html"

class SecondView(TemplateView):
    template_name = "django_tutorial/second_page.html"

class AnotherView(TemplateView):
    template_name = "django_tutorial/page_with_extra_context.html"

    def get_context_data(self, **kwargs):
        context = super(AnotherView, self).get_context_data(**kwargs)
        # Here you can add extra stuff to the context, we use this example:
        context['extra_something'] = 'Show how to use the context'
        return context

django_tutorial/templates/django_tutorial/base.html
{% load staticfiles %}
{% load i18n %}
<html>
<head>
{% block head %}
<!-- place css links here -->
<!-- <link rel="stylesheet" href="{% static 'css/django-tutorial.css' %}"> -->
  <title>Django tutorial</title>
{% endblock %}
</head>
  <body>
    {% block breadcrumps%}
      <!-- fill in later -->
    {% endblock %}
    <div class="content container">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

django_tutorial/templates/django_tutorial/home.html
{% extends "django_tutorial/base.html" %}
{% load i18n %}

{% block content %}
    <h1>Welcome to Django tutorial</h1>
    Note: the apps have namespaces, the project it selve not, the link to this page is just included to show the namespaces (very useless link to the same page now).<br>
    <br>
    <ul>
        <li><a href="{% url 'iamreusable:index' %}">Link to the index page of the reusable app</a><br></li>
        <li><a href="{% url 'exampmod:index' %}">Link to the index page of the embedded app</a><br></li>
        <li><a href="{% url 'index' %}">Link to the index page of the project (this page, so a rather useless link)</a><br></li>
    </ul>
    <br>

{% endblock %}